# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-03-18 17:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_auto_20200223_1120"),
    ]

    operations = [
        migrations.DeleteModel(name="Customer",),
    ]
