# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-03-24 16:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_auto_20200321_1145"),
    ]

    operations = [
        migrations.RemoveField(model_name="customer", name="country",),
    ]
