# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-03-18 17:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_orderhistory_orderitemhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='phone_number',
            field=models.IntegerField(max_length=20),
        ),
    ]
