# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-03-19 11:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("checkout", "0003_auto_20200318_1730"),
    ]

    operations = [
        migrations.RemoveField(model_name="order", name="phone_number",),
    ]
