# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-03-21 11:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("checkout", "0004_remove_order_phone_number"),
    ]

    operations = [
        migrations.RemoveField(model_name="orderlineitem", name="order",),
        migrations.RemoveField(model_name="orderlineitem", name="product",),
        migrations.DeleteModel(name="Order",),
        migrations.DeleteModel(name="OrderLineItem",),
    ]
