# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-03-24 16:25
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_remove_customer_country"),
        ("checkout", "0005_auto_20200321_1145"),
    ]

    operations = [
        migrations.RemoveField(model_name="orderhistory", name="user",),
        migrations.AddField(
            model_name="orderhistory",
            name="customer",
            field=models.ForeignKey(
                default=2,
                on_delete=django.db.models.deletion.CASCADE,
                to="accounts.Customer",
            ),
        ),
    ]
