# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-03-24 16:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0006_auto_20200324_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderhistory',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Customer'),
        ),
    ]
