# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-02-26 13:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category_id',
            field=models.CharField(max_length=20),
        ),
    ]
