# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-03-24 20:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0005_auto_20200226_1946"),
    ]

    operations = [
        migrations.RemoveField(model_name="product", name="quantity",),
    ]
